# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 311b03b25169f0bc7033582032e133ad25a8ebc10ef7b495c1639d577c29ee80b3ddd7cf4a9480ca6215aae048cba07e702aee5e2307901ea2698c369b0b081a

test:
  secret_key_base: 2a7860f0ff4897a34c56241381a6d94ee5d2c1f7fbaf4d45881b839129444571201e6ad26d3c3b867958b7585fabff83063c83d73db2496c373c3cbf5cf2fdc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
